"""SMS service — send/verify OTP via Twilio Verify API."""

import logging
from app.core.config import settings

logger = logging.getLogger("securejob.sms")


def send_otp_sms(to_phone: str, otp: str = None) -> bool:
    """Send an OTP via Twilio Verify API. OTP is generated by Twilio, not us."""
    if not settings.TWILIO_SID or not settings.TWILIO_AUTH_TOKEN or not settings.TWILIO_VERIFY_SID:
        logger.warning("Twilio not configured — printing OTP to console instead.")
        print(f"=== SMS OTP for {to_phone}: {otp} ===")
        return True

    try:
        from twilio.rest import Client
        from twilio.base.exceptions import TwilioRestException
        client = Client(settings.TWILIO_SID, settings.TWILIO_AUTH_TOKEN)
        verification = client.verify.v2.services(
            settings.TWILIO_VERIFY_SID
        ).verifications.create(to=to_phone, channel="sms")
        logger.info(f"Twilio Verify sent to {to_phone} (Status: {verification.status})")
        return True
    except Exception as e:
        logger.error(f"Failed to send Twilio Verify to {to_phone}: {e}")
        # If it's a Twilio Trial Account error (unverified number), fallback to printing
        if "unverified" in str(e).lower() or "trial" in str(e).lower():
            logger.warning("Twilio Trial Account restriction — printing OTP to console instead.")
            print(f"=== SMS OTP for {to_phone} (Simulation): {otp} ===")
            return True
        raise


def check_otp_sms(to_phone: str, code: str) -> bool:
    """Verify an OTP code via Twilio Verify API."""
    if not settings.TWILIO_SID or not settings.TWILIO_AUTH_TOKEN or not settings.TWILIO_VERIFY_SID:
        # Fallback: manual check is handled by the router
        return None  # signal to use local verification

    try:
        from twilio.rest import Client
        client = Client(settings.TWILIO_SID, settings.TWILIO_AUTH_TOKEN)
        verification_check = client.verify.v2.services(
            settings.TWILIO_VERIFY_SID
        ).verification_checks.create(to=to_phone, code=code)
        logger.info(f"Twilio Verify check for {to_phone}: {verification_check.status}")
        return verification_check.status == "approved"
    except Exception as e:
        logger.error(f"Twilio Verify check failed for {to_phone}: {e}")
        # If it's a Twilio Trial Account error, fallback to local database verification
        if "unverified" in str(e).lower() or "trial" in str(e).lower():
            logger.warning("Twilio Trial Account restriction — falling back to local OTP hash verification.")
            return None # returning None signals accounts.py to check the local hash
        raise
